<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('rols')->insert([
            ['id' => 1, 'nombre' => 'Administrador'],
            ['id' => 2, 'nombre' => 'Cliente'],
            ['id' => 3, 'nombre' => 'Ferretero'],
            ['id' => 4, 'nombre' => 'Domiciliario'],
        ]);

        \DB::table('users')->insert([
            ['id' => 1, 'name' => 'Administrador', 'email' => 'admin@altosentido.net', 'rol_id' => 1, 'password' => bcrypt('admin'), ],
            ['id' => 2, 'name' => 'Cliente 1', 'email' => 'cliente@altosentido.net', 'rol_id' => 2, 'password' => bcrypt('cliente'), ]
        ]);

        \DB::table('carritos')->insert([
            ['id' => 1, 'user_id' => 1, 'total' => 0.0],
            ['id' => 2, 'user_id' => 2, 'total' => 0.0 ]
        ]);

        \DB::table('estado_pedidos')->insert([
            ['id' => 1, 'nombre' => 'Creado', "css" => "info"],
            ['id' => 2, 'nombre' => 'Pendiente de pago', "css" => "primary"],
            ['id' => 3, 'nombre' => 'Procesando', "css" => "warning"],
            ['id' => 4, 'nombre' => 'En espera', "css" => "secondary"],
            ['id' => 5, 'nombre' => 'Completado', "css" => "success"],
            ['id' => 6, 'nombre' => 'Cancelado', "css" => "dark"], // De pendiente de pago a cancelado si no se paga en el tiempo permitido.
            ['id' => 7, 'nombre' => 'Reembolsado', "css" => "light"],
            ['id' => 8, 'nombre' => 'Fallido', "css" => "danger"],
            ['id' => 9, 'nombre' => 'Por Pagar - Crédito Ferretero', "css" => "info"],
        ]);

        \DB::table('estado_ferreteros')->insert([
            ['id' => 1, 'nombre' => 'Por revisar', 'css' => 'warning'],
            ['id' => 2, 'nombre' => 'Aprobada', 'css' => 'success'],
            ['id' => 3, 'nombre' => 'Rechazada', 'css' => 'error'],
            ['id' => 4, 'nombre' => 'Revisar de nuevo', 'css' => 'warning'],
        ]);

        \DB::table('productos')->insert([
            ['imagen' => 'carretilla.jpg',
            'sku' => '1',
            'categoria_id' => 7,
            'nombre' => 'Carretilla Tolva Metalica Llanta Antipinchazo',
            'slug' => 'carretilla_tolva_metalica_llanta_antipinchazo',
            'descripcion_corta' => 'Carretilla Tolva Metalica Llanta Antipinchazo',
            'cantidad' => 50,
            'precio_descuento' => null,
            'precio' => 230000.00],

            ['imagen' => 'breker.jpg',
            'sku' => '1',
            'categoria_id' => 16,
            'nombre' => 'Breaker Termomagnetico 40apm - 110v Pow40011',
            'slug' => 'breaker_termomagnetico_40apm_110v_pow40011',
            'descripcion_corta' => 'Breaker Termomagnetico 40apm - 110v Pow40011',
            'cantidad' => 50,
            'precio_descuento' => null,
            'precio' => 30000.00],

            ['imagen' => 'cerradura.jpg',
            'sku' => '1',
            'categoria_id' => 6,
            'nombre' => 'Cerradura Sobre Poner Reja Beige Derecha Vera',
            'slug' => 'cerradura_sobre_poner_reja_beige_derecha_vera',
            'descripcion_corta' => 'Cerradura Sobre Poner Reja Beige Derecha Vera',
            'cantidad' => 50,
            'precio_descuento' => null,
            'precio' => 125000.00],

            ['imagen' => 'ducha.jpg',
            'sku' => '1',
            'categoria_id' => 11,
            'nombre' => 'Ducha Electrica Dirigible 1 Temperatura 220v K-003',
            'slug' => 'ducha_electrica_dirigible_1_temperatura_220v_k_003',
            'descripcion_corta' => 'Ducha Electrica Dirigible 1 Temperatura 220v K-003',
            'cantidad' => 50,
            'precio_descuento' => null,
            'precio' => 98000.00],

            ['imagen' => 'base.jpg',
            'sku' => '1',
            'categoria_id' => 13,
            'nombre' => 'Base para pulidora ht (HT90306)',
            'slug' => 'base_para_pulidora_ht_ht90306',
            'descripcion_corta' => 'Base para pulidora ht (HT90306)',
            'cantidad' => 50,
            'precio_descuento' => null,
            'precio' => 87500.00],

            ['imagen' => 'taladro.jpg',
            'sku' => '1',
            'categoria_id' => 13,
            'nombre' => 'Taladro dewalt 1/2 710 w vvr-percutor t-profesional (0-2800 RPM)',
            'slug' => 'taladro_dewalt_1_2_710_w_vvr_percutor_t_profesional_0_2800_rpm',
            'descripcion_corta' => 'Taladro dewalt 1/2 710 w vvr-percutor t-profesional (0-2800 RPM)',
            'cantidad' => 50,
            'precio_descuento' => null,
            'precio' => 281200.00],

            ['imagen' => 'aerografo.jpg',
            'sku' => '1',
            'categoria_id' => 14,
            'nombre' => 'Aerografo ranger/hopex alta f75 g (400 ml) f-75 g-40',
            'slug' => 'aerografo_ranger_hopex_alta_f75_g_400_ml_f_75_g_40',
            'descripcion_corta' => 'Aerografo ranger/hopex alta f75 g (400 ml) f-75 g-40',
            'cantidad' => 50,
            'precio_descuento' => 55000.00,
            'precio' => 60000.00],

            ['imagen' => 'llaves.jpg',
            'sku' => '1',
            'categoria_id' => 14,
            'nombre' => 'Alem blister uduke juego x 10 pcs mm (llm010)(ht20248)',
            'slug' => 'alem_blister_uduke_juego_x_10_pcs_mm_llm010_ht20248',
            'descripcion_corta' => 'Alem blister uduke juego x 10 pcs mm (llm010)(ht20248)',
            'cantidad' => 50,
            'precio_descuento' => 5000.00,
            'precio' => 80000.00],

            ['imagen' => 'base2.jpg',
            'sku' => '1',
            'categoria_id' => 13,
            'nombre' => 'Llave para pulidora ht (HT90306)',
            'slug' => 'llave_para_pulidora_ht_ht90306',
            'descripcion_corta' => 'Llave para pulidora ht (HT90306)',
            'cantidad' => 50,
            'precio_descuento' => 84500.00,
            'precio' => 110000.00],

            ['imagen' => 'carretilla2.jpg',
            'sku' => '1',
            'categoria_id' => 7,
            'nombre' => 'Carretilla Tolva Metalica Llanta Antipinchazo',
            'slug' => 'carretilla_tolva_metalica_llanta_antipinchazo',
            'descripcion_corta' => 'Carretilla Tolva Metalica Llanta Antipinchazo',
            'cantidad' => 50,
            'precio_descuento' => 200000.00,
            'precio' => 230000.00],
        ]);

        \DB::table('categorias')->insert([
            ['nombre' => 'Sin categoria',
            'slug' => 'sin-categoria',
            'destacada' => 0,
            'categoria_id' => null],
            ['nombre' => 'ABRASIVOS',
            'slug' => 'abrasivos',
            'destacada' => 0,
            'categoria_id' => null],
            ['nombre' => 'AGRO',
            'slug' => 'agro',
            'destacada' => 0,
            'categoria_id' => null],
            ['nombre' => 'CABLES Y ELECTRICOS',
            'slug' => 'cables_y_electricos',
            'destacada' => 0,
            'categoria_id' => null],
            ['nombre' => 'BIOSEGURIDAD',
            'slug' => 'bioseguridad',
            'destacada' => 0,
            'categoria_id' => null],
            ['nombre' => 'CERRADURAS',
            'slug' => 'cerraduras',
            'destacada' => 0,
            'categoria_id' => null],
            ['nombre' => 'CONSTRUCCIÓN',
            'slug' => 'construcción',
            'destacada' => 1,
            'categoria_id' => null],
            ['nombre' => 'DISCOS Y BROCAS',
            'slug' => 'discos_y_brocas',
            'destacada' => 0,
            'categoria_id' => null],
            ['nombre' => 'ELECTRODOMÉSTICOS',
            'slug' => 'electrodomésticos',
            'destacada' => 1,
            'categoria_id' => null],
            ['nombre' => 'GRAMERAS',
            'slug' => 'grameras',
            'destacada' => 0,
            'categoria_id' => null],
            ['nombre' => 'GRIFERÍA',
            'slug' => 'grifería',
            'destacada' => 1,
            'categoria_id' => null],
            ['nombre' => 'HERRAMIENTRAS AUTOMOTRIZ',
            'slug' => 'herramientras_automotriz',
            'destacada' => 1,
            'categoria_id' => null],
            ['nombre' => 'HERRAMIENTA ELECTRÍCAS',
            'slug' => 'herramienta_electrícas',
            'destacada' => 1,
            'categoria_id' => null],
            ['nombre' => 'HERRAMIENTA MANUAL',
            'slug' => 'herramienta_manual',
            'destacada' => 1,
            'categoria_id' => null],
            ['nombre' => 'HOGAR',
            'slug' => 'hogar',
            'destacada' => 1,
            'categoria_id' => null],
            ['nombre' => 'ILUMINACIÓN',
            'slug' => 'iluminación',
            'destacada' => 1,
            'categoria_id' => null],
            ['nombre' => 'LLAVES',
            'slug' => 'llaves',
            'destacada' => 0,
            'categoria_id' => null],
            ['nombre' => 'PINTURAS Y SOLVENTES',
            'slug' => 'pinturas_y_solventes',
            'destacada' => 0,
            'categoria_id' => null],
            ['nombre' => 'RODACHINES',
            'slug' => 'rodachines',
            'destacada' => 0,
            'categoria_id' => null],
            ['nombre' => 'SEGURIDAD INDUSTRIAL',
            'slug' => 'seguridad_industrial',
            'destacada' => 0,
            'categoria_id' => null],
            ['nombre' => 'SERVICIOS',
            'slug' => 'servicios',
            'destacada' => 0,
            'categoria_id' => null],
            ['nombre' => 'SILICONAS Y ADHESIVOS',
            'slug' => 'siliconas_y_adhesivos',
            'destacada' => 0,
            'categoria_id' => null],
            ['nombre' => 'SOPORTES Y HERRAJES',
            'slug' => 'soportes_y_herrajes',
            'destacada' => 0,
            'categoria_id' => null],
            ['nombre' => 'TOMAS E INTERRUPTORES',
            'slug' => 'tomas_e_interruptores',
            'destacada' => 0,
            'categoria_id' => null],
            ['nombre' => 'OTROS',
            'slug' => 'otros',
            'destacada' => 0,
            'categoria_id' => null],
        ]);
        \DB::table('categorias')->insert([
            ['nombre' => 'Alicates y Hombresolo',
            'slug' => 'alicates_y_hombresolo',
            'imagen' => 'alicate.jpg',
            'destacada' => 0,
            'categoria_id' => 14],
            ['nombre' => 'Navajas',
            'slug' => 'navajas',
            'imagen' => 'navajas.jpg',
            'destacada' => 0,
            'categoria_id' => 14],
            ['nombre' => 'Kits de herramientas',
            'slug' => 'kits_de_herramientas',
            'imagen' => 'kits.jpg',
            'destacada' => 0,
            'categoria_id' => 14],
            ['nombre' => 'Destornilladores',
            'slug' => 'destornilladores',
            'imagen' => 'destornillador.jpg',
            'destacada' => 0,
            'categoria_id' => 14],
            ['nombre' => 'Llaves',
            'slug' => 'llaves',
            'imagen' => 'llaves.jpg',
            'destacada' => 0,
            'categoria_id' => 14],
            ['nombre' => 'Serruchos y seguetas',
            'slug' => 'serruchos_y_seguetas',
            'imagen' => 'serrucho.jpg',
            'destacada' => 0,
            'categoria_id' => 14],
            ['nombre' => 'Remachadoras',
            'slug' => 'remachadoras',
            'imagen' => 'remachadora.jpg',
            'destacada' => 0,
            'categoria_id' => 14],
            ['nombre' => 'Martillos y mazos',
            'slug' => 'martillos_y_mazos',
            'imagen' => 'martillo.jpg',
            'destacada' => 0,
            'categoria_id' => 14],
            ['nombre' => 'Grapadoras y accesorios',
            'slug' => 'grapadoras_y_accesorios',
            'imagen' => 'grapadoras.jpg',
            'destacada' => 0,
            'categoria_id' => 14],
            ['nombre' => 'Otras herramientas manuales',
            'slug' => 'otras_herramientas_manuales',
            'imagen' => 'otras.jpg',
            'destacada' => 0,
            'categoria_id' => 14],
        ]);
        \DB::table('etiquetas')->insert([
            ['nombre' => 'Insuperables',
            'slug' => 'insuperables'],
            ['nombre' => 'Oferta',
            'slug' => 'oferta'],
            ['nombre' => 'Novedades',
            'slug' => 'Novedades'],
            ['nombre' => 'Más Vendido',
            'slug' => 'mas-vendido'],
            // ['nombre' => 'Día del padre',
            // 'slug' => 'dia-del-padre'],
        ]);
        \DB::table('etiqueta_producto')->insert([
            ['etiqueta_id' => 1, 'producto_id' => 1],
            ['etiqueta_id' => 1, 'producto_id' => 2],
            ['etiqueta_id' => 1, 'producto_id' => 3],
            ['etiqueta_id' => 1, 'producto_id' => 4],
            ['etiqueta_id' => 1, 'producto_id' => 5],
            ['etiqueta_id' => 1, 'producto_id' => 6],
            ['etiqueta_id' => 1, 'producto_id' => 7],
            ['etiqueta_id' => 2, 'producto_id' => 8],
            ['etiqueta_id' => 2, 'producto_id' => 9],
            ['etiqueta_id' => 2, 'producto_id' => 10],
            ['etiqueta_id' => 2, 'producto_id' => 11],
            ['etiqueta_id' => 3, 'producto_id' => 1],
            ['etiqueta_id' => 3, 'producto_id' => 2],
            ['etiqueta_id' => 3, 'producto_id' => 3],
            ['etiqueta_id' => 3, 'producto_id' => 4],
            ['etiqueta_id' => 3, 'producto_id' => 5],
            ['etiqueta_id' => 3, 'producto_id' => 6],
            ['etiqueta_id' => 3, 'producto_id' => 7],
            ['etiqueta_id' => 4, 'producto_id' => 7],
            ['etiqueta_id' => 4, 'producto_id' => 8],
            ['etiqueta_id' => 4, 'producto_id' => 9],
            ['etiqueta_id' => 4, 'producto_id' => 10],
        ]);

        \DB::table('departamentos')->insert([
            ['nombre' => 'Valle del Cauca'],
            ['nombre' => 'Quindio'],
        ]);
        \DB::table('ciudads')->insert([
            ['nombre' => 'Cali', 'departamento_id' => 1],
            ['nombre' => 'Armenia', 'departamento_id' => 2],
        ]);

        \DB::table('medio_transportes')->insert([
            [
                'nombre' => 'Envío Express',
                'ancho' => 60,
                'alto' => 40,
                'largo' => 40,
                'peso' => 1500,
                'precio' => 0,
            ],
            [
                'nombre' => 'camión',
                'ancho' => 2500,
                'alto' => 2500,
                'largo' => 3500,
                'peso' => 5000,
                'precio' => 10000,
            ]
        ]);

        \DB::table('atributos')->insert([
            ['nombre' => 'Marcas', 'slug' => 'marcas', 'activo' => 1],
        ]);

        \DB::table('terminos')->insert([
            ['nombre' => 'Makita', 'imagen' => 'generica.png', 'atributo_id' => 1, 'activo' => 1],
        ]);
    }
}
